analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**_test_**.dart
    - lib/**.config.dart

linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes
    - avoid_print
    - unnecessary_new

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml


